"use client";

/**
 * @typedef {object} CampaignData
 * @property {string} campaign - The name of the campaign.
 * @property {number} adSpend - The advertising spend for the campaign.
 * @property {number} sales - The sales generated by the campaign.
 * @property {number} [acos] - Advertising Cost of Sales (ACoS).
 * @property {number} [roas] - Return on Ad Spend (ROAS).
 * @property {number} [impressions] - Number of impressions.
 * @property {number} [clicks] - Number of clicks.
 * @property {number} [ctr] - Click-Through Rate (CTR).
 * @property {number} [cpc] - Cost Per Click (CPC).
 * @property {number} [conversionRate] - Conversion Rate.
 */
export type CampaignData = {
  campaign: string;
  adSpend: number;
  sales: number;
  acos?: number;
  roas?: number;
  impressions?: number;
  clicks?: number;
  ctr?: number;
  cpc?: number;
  conversionRate?: number;
};

/**
 * @typedef {object} TrendData
 * @property {number} previousPeriodSales - Sales from the previous period for trend analysis.
 * @property {number} previousPeriodAdSpend - Ad spend from the previous period for trend analysis.
 * @property {number} [industryAverageCTR] - Industry average Click-Through Rate for comparison.
 * @property {number} [industryAverageConversion] - Industry average Conversion Rate for comparison.
 * @property {number} [seasonalityFactor] - Factor to adjust for seasonal variations (e.g., 1.1 for 10% seasonal uplift).
 * @property {"rising" | "stable" | "declining"} [marketTrend] - General market trend.
 * @property {"low" | "medium" | "high"} [competitionLevel] - Level of competition in the market.
 */
export interface TrendData {
  previousPeriodSales: number;
  previousPeriodAdSpend: number;
  industryAverageCTR?: number;
  industryAverageConversion?: number;
  seasonalityFactor?: number;
  marketTrend?: "rising" | "stable" | "declining";
  competitionLevel?: "low" | "medium" | "high";
}

/**
 * Calculates key advertising metrics (ACoS, ROAS, CTR, CPC, Conversion Rate) for a given campaign.
 * Optionally incorporates trend data for more nuanced and adjusted metric calculations.
 *
 * @param {Pick<CampaignData, "adSpend" | "sales" | "impressions" | "clicks">} data - The core campaign data needed for calculations.
 * @param {TrendData} [trendData] - Optional trend data to influence metric calculations.
 * @returns {Omit<CampaignData, "campaign" | "adSpend" | "sales">} An object containing the calculated metrics.
 */
export const calculateMetrics = (
  data: Pick<CampaignData, "adSpend" | "sales" | "impressions" | "clicks">,
  trendData?: TrendData,
): Omit<CampaignData, "campaign" | "adSpend" | "sales"> => {
  const { adSpend, sales, impressions, clicks } = data;

  // Calculate fundamental metrics: ACoS (Advertising Cost of Sales) and ROAS (Return on Ad Spend)
  const metrics: Omit<CampaignData, "campaign" | "adSpend" | "sales"> = {
    acos: (adSpend / sales) * 100, // ACoS = (Ad Spend / Sales) * 100
    roas: sales / adSpend, // ROAS = Sales / Ad Spend
  };

  // Calculate Click-Through Rate (CTR) if impressions and clicks data are available.
  // Includes an optional adjustment based on industry average CTR for more nuanced performance evaluation.
  if (impressions && clicks) {
    const rawCTR = (clicks / impressions) * 100;
    metrics.ctr = rawCTR;

    if (trendData?.industryAverageCTR) {
      // Adjust CTR score: A higher ratio to industry average means better performance,
      // which is weighted to influence the final CTR metric.
      const ctrPerformanceRatio = rawCTR / trendData.industryAverageCTR;
      metrics.ctr = rawCTR * (0.7 + ctrPerformanceRatio * 0.3); // Weighted adjustment
    }
  }

  // Calculate Conversion Rate and Cost Per Click (CPC) if clicks data is available.
  // Conversion rate also includes an optional adjustment based on industry average.
  if (clicks) {
    const rawConversionRate = (sales / clicks) * 100;
    metrics.conversionRate = rawConversionRate;

    if (trendData?.industryAverageConversion) {
      // Adjust conversion score: Similar to CTR, a better ratio to industry average
      // positively influences the conversion rate metric.
      const conversionPerformanceRatio =
        rawConversionRate / trendData.industryAverageConversion;
      metrics.conversionRate =
        rawConversionRate * (0.7 + conversionPerformanceRatio * 0.3); // Weighted adjustment
    }

    metrics.cpc = adSpend / clicks; // CPC = Ad Spend / Clicks
  }

  // Incorporate trend-based analysis to provide a more dynamic ACoS metric.
  // This section considers historical performance, seasonality, market trends, and competition.
  if (trendData) {
    const salesGrowth =
      ((sales - trendData.previousPeriodSales) /
        trendData.previousPeriodSales) *
      100;
    const adSpendGrowth =
      ((adSpend - trendData.previousPeriodAdSpend) /
        trendData.previousPeriodAdSpend) *
      100;

    // Define weights for different factors influencing the overall performance score.
    const performanceWeight = 0.6; // Primary weight for current performance
    const seasonalityWeight = 0.2; // Weight for seasonal impact
    const marketTrendWeight = 0.2; // Weight for general market direction

    // Calculate a base trend factor based on sales and ad spend growth.
    let trendFactor = 1 + (salesGrowth - adSpendGrowth) / 100;

    // Adjust trend factor based on seasonality.
    if (trendData.seasonalityFactor) {
      trendFactor *= 1 + (trendData.seasonalityFactor - 1) * seasonalityWeight;
    }

    // Adjust trend factor based on overall market trend.
    if (trendData.marketTrend) {
      const marketTrendImpact = {
        rising: 1.1, // Positive impact for rising markets
        stable: 1.0, // Neutral impact for stable markets
        declining: 0.9, // Negative impact for declining markets
      }[trendData.marketTrend];
      trendFactor *= 1 + (marketTrendImpact - 1) * marketTrendWeight;
    }

    // Adjust trend factor based on competition level.
    if (trendData.competitionLevel) {
      const competitionImpact = {
        low: 0.95, // Slightly positive for low competition
        medium: 1.0, // Neutral for medium competition
        high: 1.05, // Slightly negative for high competition
      }[trendData.competitionLevel];
      trendFactor *= competitionImpact;
    }

    // Calculate the final ACoS by blending the base ACoS with an adjusted ACoS
    // that incorporates the calculated trend factor. The Math.max/min ensures
    // the trend factor remains within a reasonable range to prevent extreme values.
    const baseAcos = metrics.acos;
    const adjustedAcos =
      baseAcos * (1 / Math.max(0.8, Math.min(1.2, trendFactor)));
    metrics.acos =
      baseAcos * (1 - performanceWeight) + adjustedAcos * performanceWeight;
  }

  return metrics;
};

/**
 * Determines the ACoS rating based on a given ACoS percentage.
 * @param {number} acos - The ACoS percentage.
 * @returns {string} The ACoS rating (e.g., "Excellent", "Good", "Critical").
 */
export const getAcosRating = (acos: number): string => {
  if (acos < 15) return "Excellent";
  if (acos < 25) return "Good";
  if (acos < 35) return "Average";
  if (acos < 45) return "Poor";
  return "Critical";
};

/**
 * Determines the color associated with an ACoS percentage for visual representation.
 * @param {number} acos - The ACoS percentage.
 * @returns {"green" | "emerald" | "yellow" | "orange" | "red"} The color string.
 */
export const getAcosColor = (
  acos: number,
): "green" | "emerald" | "yellow" | "orange" | "red" => {
  if (acos < 15) return "green";
  if (acos < 25) return "emerald";
  if (acos < 35) return "yellow";
  if (acos < 45) return "orange";
  return "red";
};

/**
 * Configuration for chart data, mapping metric keys to display labels and themes.
 * @constant
 * @type {object}
 * @property {object} acos - ACoS chart configuration.
 * @property {string} acos.label - Label for ACoS on charts.
 * @property {object} acos.theme - Theme colors for ACoS.
 * @property {string} acos.theme.light - Light theme color.
 * @property {string} acos.theme.dark - Dark theme color.
 * @property {object} roas - ROAS chart configuration.
 * @property {string} roas.label - Label for ROAS on charts.
 * @property {object} roas.theme - Theme colors for ROAS.
 * @property {string} roas.theme.light - Light theme color.
 * @property {string} roas.theme.dark - Dark theme color.
 * @property {object} ctr - CTR chart configuration.
 * @property {string} ctr.label - Label for CTR on charts.
 * @property {object} ctr.theme - Theme colors for CTR.
 * @property {string} ctr.theme.light - Light theme color.
 * @property {string} ctr.theme.dark - Dark theme color.
 * @property {object} cpc - CPC chart configuration.
 * @property {string} cpc.label - Label for CPC on charts.
 * @property {object} cpc.theme - Theme colors for CPC.
 * @property {string} cpc.theme.light - Light theme color.
 * @property {string} cpc.theme.dark - Dark theme color.
 */
export const chartConfig = {
  acos: {
    label: "ACoS %",
    theme: { light: "#ef4444", dark: "#f87171" },
  },
  roas: {
    label: "ROAS",
    theme: { light: "#22c55e", dark: "#4ade80" },
  },
  ctr: {
    label: "CTR %",
    theme: { light: "#3b82f6", dark: "#60a5fa" },
  },
  cpc: {
    label: "CPC $",
    theme: { light: "#a855f7", dark: "#c084fc" },
  },
} as const;

/**
 * Guide for ACoS ratings, including labels, ranges, and associated colors.
 * @constant
 * @type {Array<object>}
 * @property {string} label - The rating label (e.g., "Excellent").
 * @property {string} range - The ACoS percentage range for the rating.
 * @property {string} color - The color associated with the rating.
 */
export const acosRatingGuide = [
  {
    label: "Excellent",
    range: "<15%",
    color: "green",
  },
  {
    label: "Good",
    range: "15-25%",
    color: "emerald",
  },
  {
    label: "Average",
    range: "25-35%",
    color: "yellow",
  },
  {
    label: "Poor",
    range: "35-45%",
    color: "orange",
  },
  { label: "Critical", range: ">45%", color: "red" },
] as const;
